In [65]:
import pandas as pd
from io import StringIO

flows_ptes = pd.DataFrame({
    'source': ['Field3', 'PTES', 'PTES', 'Tank', 'PTES', 'Energy-Change'], 
    'target': ['PTES', 'Heat-Pump', 'Tank', 'PTES', 'Loss', 'PTES'], 
    'value': [10141, 7733, 7733, 10141, 4615, 212],
    'type': [1, 2, 3, 4, 0, 0]
})

flows_ptes

          source     target  value  type
0         Field3       PTES  10141     1
1           PTES  Heat-Pump   7733     2
2           PTES       Tank   7733     3
3           Tank       PTES  10141     4
4           PTES       Loss   4615     0
5  Energy-Change       PTES    212     0

In [66]:
from floweaver import *

# Set the default size to fit the documentation better.
size = dict(width=570, height=300)

nodes = {
    'input': ProcessGroup(['Field3', 'Tank', 'Energy-Change']),
    'PTES': ProcessGroup(['PTES']),
    'output': ProcessGroup(['Heat-Pump', 'Tank', 'Loss']),
}

nodes['input'].partition = Partition.Simple('process', [
    'Field3', 'Tank', 'Energy-Change'
])

nodes['output'].partition = Partition.Simple('process', [
    'Heat-Pump', 'Tank', 'Loss'
])

bundles = [
    Bundle('input', 'PTES'),
    Bundle('PTES', 'output'),
]

ordering = [
    ['input'],
    ['PTES'],
    ['output'],
]

sdd = SankeyDefinition(nodes, bundles, ordering)

weave(sdd, flows_ptes).to_widget(**size)

SankeyWidget(groups=[{'id': 'input', 'type': 'process', 'title': '', 'nodes': ['input^Field3', 'input^Tank', '…

In [68]:
flows_tank = pd.DataFrame({
    'source': ['Tank', 'Tank', 'Field12', 'PTES', 'Boiler', 'Tank', 'Energy-Change'], 
    'target': ['DHN1', 'DHN2', 'Tank', 'Tank', 'Tank', 'Loss', 'Tank'], 
    'value': [47545.5, 47545.5, 31848.33, 31848.33, 31848.33, 453, 0.28],
    'port': [1, 2, 3, 4, 5, 0, 0]
})

flows_tank

          source target     value  port
0           Tank   DHN1  47545.50     1
1           Tank   DHN2  47545.50     2
2        Field12   Tank  31848.33     3
3           PTES   Tank  31848.33     4
4         Boiler   Tank  31848.33     5
5           Tank   Loss    453.00     0
6  Energy-Change   Tank      0.28     0

In [69]:
nodes = {
    'input': ProcessGroup(['Tank', 'Field12', 'PTES', 'Boiler', 'Energy-Change']),
    'Tank': ProcessGroup(['Tank']),
    'output': ProcessGroup(['DHN1', 'DHN2', 'Tank', 'Loss']),
}

nodes['input'].partition = Partition.Simple('process', [
    'Tank', 'Field12', 'PTES', 'Boiler', 'Energy-Change'
])

nodes['output'].partition = Partition.Simple('process', [
    'DHN1', 'DHN2', 'Tank', 'Loss'
])

bundles = [
    Bundle('input', 'Tank'),
    Bundle('Tank', 'output'),
]

ordering = [
    ['input'],
    ['Tank'],
    ['output'],
]

sdd = SankeyDefinition(nodes, bundles, ordering)

weave(sdd, flows_tank).to_widget(**size)

SankeyWidget(groups=[{'id': 'input', 'type': 'process', 'title': '', 'nodes': ['input^Field12', 'input^PTES', …